import {
  IconDown,
  IconUp,
  FacebookIcon,
  TwitterIcon,
  InstaIcon,
  YoutubeIcon,
} from "./assets";

export const overviewData = [
  {
    name: "page views",
    socialIcon: FacebookIcon,
    num: "87",
    icon: IconUp,
    positive: true,
    status: "3%",
  },
  {
    name: "likes",
    socialIcon: FacebookIcon,
    num: "52",
    icon: IconDown,
    positive: false,
    status: "2%",
  },
  {
    name: "likes",
    socialIcon: InstaIcon,
    num: "5462",
    icon: IconUp,
    positive: true,
    status: "2257%",
  },
  {
    name: "profile views",
    socialIcon: InstaIcon,
    num: "52k",
    icon: IconUp,
    positive: true,
    status: "1375%",
  },
  {
    name: "retweets",
    socialIcon: TwitterIcon,
    num: "117",
    icon: IconUp,
    positive: true,
    status: "303%",
  },
  {
    name: "likes",
    socialIcon: TwitterIcon,
    num: "507",
    icon: IconUp,
    positive: true,
    status: "553%",
  },
  {
    name: "likes",
    socialIcon: YoutubeIcon,
    num: "107",
    icon: IconDown,
    positive: false,
    status: "19%",
  },
  {
    name: "total views",
    socialIcon: YoutubeIcon,
    num: "1407",
    icon: IconDown,
    positive: false,
    status: "12%",
  },
];
